### ISSUE TITLE
Problem 2 - Developer

### ISSUE THREAD

**Issue by saiaungkyawmaw** [Bug-Busters-UNCC-ITSC3155/Project3#5]
As a developer, these are the requirements that need to be met for problem 2
- [x] Create JavaScript Class : TableTemplate.js
- [x] static method - fillIn

requirements for fill_In method

- [x] This method takes three arguments consisting of the id attribute for a <table>, a dictionary object, and a string columnName.

- [ ] The method must first examine the header row of the table and and replace any text of the form {{property}} with the corresponding property of the dictionary object. It then fills in all {{property}} elements in the column specified by columnName if there exists such a column.

- [ ] The method assumes that the first row of the table holds the column names. You are guaranteed that the column names of the input table are unique.

- [ ] If no columnName argument is specified, the method should process the entire table.

- [ ] If the specified columnName is not matched, the method should return without replacing any text in the columns. Note that you should still replace template strings in the header row regardless of whether the specified columnName is matched.

Note.
You should use your template-processor.js solution from project 2 to help you implement the fillIn method. See the script tag ordering in the html file in the project3 directory to see how your template-processor.js code would be loaded.

**Comment by AnshukGottipati** [comment]
Doing this
